#!/bin/bash

#SBATCH --partition=pcbg-compute               # Uses cardiology node
#SBATCH --account=pcbg
#SBATCH --qos=unlimited
#SBATCH --time=24:00:00                         # Running time (in hours-minute-seconds)  
#SBATCH --mail-type=BEGIN,END,FAIL              # send and email when the job begins, ends or fails
#SBATCH --output=outputs/output_%j.txt                  # Name of the output file
#SBATCH --nodes=1                               # Number of compute nodes
#SBATCH --ntasks=24                             # Number of cpu cores on one node
#SBATCH	--mem=64G					# mem-per-cpu=16G

module load matlab
export CONDA_ENVS_PATH="$HOME/.conda/envs/"

#activates the cellpose environment with Python 3.10
source activate cellpose

#mkdir -p $1/for_matlab/
mkdir -p $1/matlab_output/
#mkdir -p $1/for_segmentation/
#mkdir -p $1/for_segmentation/std/
#mkdir -p $1/for_segmentation/downsample/

#python image_prep_PEAR.py $1

#python -m cellpose --dir $1/for_segmentation/std --pretrained_model cyto3 --diameter 0 --chan 0 --verbose --norm_percentile 1.0 99.0 --no_norm --save_tif --no_npy

mv $1/for_segmentation/std/*masks.tif $1/for_segmentation/downsample

python ca_roi_time_PEAR.py $1 $4

mv $1/for_segmentation/downsample/*.csv $1/for_matlab

for filename in ${1}/for_matlab/*downsample.csv
do matlab -nodisplay -nosplash -nodesktop -r "addpath('CaTScan_analysis_matlab'); AP_run_analysis_XLV('${filename}', ['$1','/for_matlab/parameters.csv'],['$1','/matlab_output/'],${2:-0.05},${3:-0.1});exit;"
done

cd $1/matlab_output/
awk '(NR == 1) || (FNR > 1)' *.csv > combined_results.csv

#remove /scan file.****disabled*****
#rm -rf $1/scan/
